### ISSUE TITLE
Wildcard in a query target

### ISSUE THREAD

**Issue by doublemarket** [doublemarket/grafana-rrd-server#22]
e.g. Giving `mysql.query_count.*` as a target in a query, then the query endpoint returns datapoints of `mysql.query_count.select`, `mysql.query_count.update` and so on.

**Comment by doublemarket** [comment]
Closing as #23 merged

**Comment by majekw** [comment]
A note for Muinin users: query needs `ds` field to work, so it should be like this: `group:host-metric-*:42`.
This doesn't work and causes grafana-rrd-server panic: `group:host-metric-*`
