### ISSUE TITLE
Graph aggregation / item renaming

### ISSUE THREAD

**Issue by Anon1234** [doublemarket/grafana-rrd-server#32]
Hello,

I'm not sure if my question related more to your project or [simple json datasource](https://github.com/grafana/simple-json-datasource), but here it is: is there a way to get a agregated graph from two values, let say, uplink A usage and uplink B usage -> Total Uplink usage graph?

As far as I see, there is no way to do so, or even simply to rename item:
![screenshot from 2017-10-01 23-05-52](https://user-images.githubusercontent.com/1951834/31058493-2f693108-a6fd-11e7-9f62-f56d7745b5c2.png)

Thank you in advance for the answer.

**Comment by doublemarket** [comment]
Hello @Anon1234 👋

I think what you want is the [`sumSeries`](https://graphite-web.readthedocs.io/en/latest/functions.html#graphite.render.functions.sumSeries) function in Graphite which adds up metrics and returns the sum. I think this should be done not on the simple json plugin but on grafana-rrd-server. However, there's no concrete plan to implement functions into it.

**Comment by Anon1234** [comment]
Thank for your answer.

**Comment by sam5558** [comment]
Sorry to reopen this issue, but i'm interested to know if there has been any update on aggregating metrics from grafana-rrd-server datasource ?

Actually i wanted to be able to aggregate two metrics or any arithmetic operation between metrics using grafana-rrd-server, like what you said @Anon1234.

sumSeries is unfortunately only usable with graphite datasource.

Also, is it possible to store the output metric in a variable that i can call somewhere else ; `count = metric1`. then call `count` & fetch current values?
