### ISSUE TITLE
Execute ./grafana-rrd-server

### ISSUE THREAD

**Issue by DRFP** [doublemarket/grafana-rrd-server#42]
I'm using CentOS 6.9.
When i execute ./grafana-rrd-server it gives the error:
./grafana-rrd-server: line 1: syntax error near unexpected token `newline'
./grafana-rrd-server: line 1: '!DOCTYPE html'

Please help me.

**Comment by doublemarket** [comment]
@DRFP Hi 👋 

I think what you downloaded is not the binary but a file containing HTML in it. If you want a binary file you can directly execute, download [the archive file](https://github.com/doublemarket/grafana-rrd-server/releases/download/v0.0.5/grafana-rrd-server_linux_amd64.gz), extract the archive by running `gzip [filename]`, and run the extracted file.
